server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: eat_easy
    password: easy
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5

  jackson:
    serialization:
      indent_output: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

logging:
  level:
    root: info

