server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: product-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5

  jackson:
    serialization:
      indent_output: true

  cloud:
    consul:
      host: ${CONSUL_HOST:127.0.0.1}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${random.value}
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        scheme: http
        deregister: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true
    path: /product-swagger/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /product-swagger/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    root: info

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_LOGIN}
  secret-key: ${MINIO_PASSWORD}
  bucket-name: product
  avatar-folder: products-images
  bucket-policy-template: >
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": { "AWS": ["*"] },
          "Action": [ "s3:GetObject" ],
          "Resource": [ "arn:aws:s3:::%s/*" ]
        }
      ]
    }

custom:
  swagger:
    server: ${CUSTOM_SWAGGER_SERVER:http://localhost:8080}
