spring:
  application:
    name: authentication-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: authentication
  cloud:
    consul:
      discovery:
        ip-address: host.docker.internal

jwt:
  tokens:
    access:
      expiration: 3m
      key:
        private-key: classpath:/security/access_private.pem
        public-key: classpath:/security/access_public.pem
    refresh:
      expiration: 10m
      key:
        private-key: classpath:/security/refresh_private.pem
        public-key: classpath:/security/refresh_public.pem