spring:
  application:
    name: authentication-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 3s

jwt:
  mode: server
  login-url: /api/v1/auth/login
  refresh-url: /api/v1/auth/refresh
  logout-url: /api/v1/auth/logout
  issuer: authentication-service
  tokens:
    access:
      header: Authorization
      prefix: "Bearer "
      expiration: 7m
      key:
        algorithm: RSA
        private-key: ${JWT_ACCESS_PRIVATE_KEY}
        public-key: ${JWT_ACCESS_PUBLIC_KEY}
    refresh:
      use-cookie: true
      cookie-name: refresh_token
      expiration: 48h
      key:
        algorithm: RSA
        private-key: ${JWT_REFRESH_PRIVATE_KEY}
        public-key: ${JWT_REFRESH_PUBLIC_KEY}

custom:
  repository:
    refresh-token:
      key-prefix: "refresh:"