server:
  port: 8080

springdoc:
  swagger-ui:
    config-url: /api-docs-config.json
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: ${CONSUL_HOST:127.0.0.1}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service-user-orders
          uri: lb://order-service
          predicates:
            - Path=/api/v1/users/*/orders/**

        - id: order-service-orders
          uri: lb://order-service
          predicates:
              - Path=/api/v1/orders/**
        - id: order-service-swagger
          uri: lb://order-service
          predicates:
              - Path=/order-swagger/**

        - id: cart-service-user-carts
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/users/*/carts/**

        - id: cart-service-carts
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/carts/**

        - id: cart-service-swagger
          uri: lb://cart-service
          predicates:
            - Path=/cart-swagger/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-swagger/**

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**

        - id: authentication-swagger
          uri: lb://authentication-service
          predicates:
              - Path=/authentication-swagger/**

        - id: product-service-products
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: product-service-categories
          uri: lb://product-service
          predicates:
            - Path=/api/v1/categories/**

        - id: product-service-swagger
          uri: lb://product-service
          predicates:
            - Path=/product-swagger/**